-- Enriquece o Book Paris & Lisboa com locais, pontos no mapa e horários iniciais.
-- Os horários são referências editáveis pelo usuário.
do $$
declare target_user uuid; trip_id_var uuid;
begin
  select id into target_user from auth.users where lower(email)=lower('cintiapfs@gmail.com') limit 1;
  select id into trip_id_var from public.trips where user_id=target_user and name='Paris & Lisboa' limit 1;
  if trip_id_var is null then raise exception 'Viagem não encontrada para esta conta.'; end if;
  update public.activities a set title='Chegada ao Hotel Jardim Lisboa', place_name='Chegada ao Hotel Jardim Lisboa / Elevador de Santa Justa', latitude=38.7128, longitude=-9.1393, starts_at='2026-11-19T14:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=1) and a.period='afternoon';
  update public.activities a set title='Baixa, Praça do Comércio e Time Out Market Lisboa', place_name='Baixa, Praça do Comércio e Time Out Market Lisboa', latitude=38.7069, longitude=-9.1451, starts_at='2026-11-19T19:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=1) and a.period='night';
  update public.activities a set title='Castelo de São Jorge', place_name='Castelo de São Jorge / Alfama', latitude=38.7139, longitude=-9.1335, starts_at='2026-11-20T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=2) and a.period='morning';
  update public.activities a set title='Aeroporto de Lisboa — voo para Paris', place_name='Aeroporto de Lisboa — voo para Paris', latitude=38.7756, longitude=-9.1354, starts_at='2026-11-20T17:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=2) and a.period='afternoon';
  update public.activities a set title='Yooma Urban Lodge Paris', place_name='Yooma Urban Lodge Paris', latitude=48.8483, longitude=2.2935, starts_at='2026-11-20T23:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=2) and a.period='night';
  update public.activities a set title='Trocadéro e Torre Eiffel', place_name='Trocadéro e Torre Eiffel', latitude=48.8626, longitude=2.287, starts_at='2026-11-21T09:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=3) and a.period='morning';
  update public.activities a set title='Arco do Triunfo e Champs-Élysées', place_name='Arco do Triunfo e Champs-Élysées', latitude=48.8738, longitude=2.295, starts_at='2026-11-21T14:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=3) and a.period='afternoon';
  update public.activities a set title='Pont de l’Alma', place_name='Pont de l’Alma / Bateaux-Mouches', latitude=48.8622, longitude=2.301, starts_at='2026-11-21T19:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=3) and a.period='night';
  update public.activities a set title='Museu do Louvre', place_name='Museu do Louvre', latitude=48.8606, longitude=2.3376, starts_at='2026-11-22T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=4) and a.period='morning';
  update public.activities a set title='Galeries Lafayette Haussmann', place_name='Galeries Lafayette Haussmann', latitude=48.8738, longitude=2.332, starts_at='2026-11-22T14:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=4) and a.period='afternoon';
  update public.activities a set title='Ópera Garnier', place_name='Ópera Garnier / Boulevard Haussmann', latitude=48.8719, longitude=2.3316, starts_at='2026-11-22T19:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=4) and a.period='night';
  update public.activities a set title='Grande Galerie de l’Évolution — Jardin des Plantes', place_name='Grande Galerie de l’Évolution — Jardin des Plantes', latitude=48.843, longitude=2.356, starts_at='2026-11-23T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=5) and a.period='morning';
  update public.activities a set title='Panteão e Quartier Latin', place_name='Panteão e Quartier Latin', latitude=48.8462, longitude=2.346, starts_at='2026-11-23T14:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=5) and a.period='afternoon';
  update public.activities a set title='Jardim de Luxemburgo', place_name='Jardim de Luxemburgo', latitude=48.8462, longitude=2.3372, starts_at='2026-11-23T18:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=5) and a.period='night';
  update public.activities a set title='Disney Adventure World — Disneyland Paris', place_name='Disney Adventure World — Disneyland Paris', latitude=48.867, longitude=2.783, starts_at='2026-11-24T09:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=6) and a.period='morning';
  update public.activities a set title='Bistrot Chez Rémy — Disneyland Paris', place_name='Bistrot Chez Rémy — Disneyland Paris', latitude=48.867, longitude=2.783, starts_at='2026-11-24T12:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=6) and a.period='afternoon';
  update public.activities a set title='PYM Kitchen — Marvel Avengers Campus', place_name='PYM Kitchen — Marvel Avengers Campus', latitude=48.867, longitude=2.783, starts_at='2026-11-24T17:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=6) and a.period='night';
  update public.activities a set title='Place de l’Estrapade', place_name='Place de l’Estrapade', latitude=48.844, longitude=2.348, starts_at='2026-11-25T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=7) and a.period='morning';
  update public.activities a set title='Terra Nera', place_name='Terra Nera', latitude=48.844, longitude=2.347, starts_at='2026-11-25T13:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=7) and a.period='afternoon';
  update public.activities a set title='Marais', place_name='Marais', latitude=48.857, longitude=2.361, starts_at='2026-11-25T19:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=7) and a.period='night';
  update public.activities a set title='Montmartre, Place du Tertre e Sacré-Cœur', place_name='Montmartre, Place du Tertre e Sacré-Cœur', latitude=48.8867, longitude=2.3431, starts_at='2026-11-26T14:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=8) and a.period='afternoon';
  update public.activities a set title='Parque dos Príncipes', place_name='Parque dos Príncipes', latitude=48.8414, longitude=2.253, starts_at='2026-11-26T19:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=8) and a.period='night';
  update public.activities a set title='Palácio de Versalhes', place_name='Palácio de Versalhes', latitude=48.8049, longitude=2.1204, starts_at='2026-11-27T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=9) and a.period='morning';
  update public.activities a set title='Jardins de Versalhes', place_name='Jardins de Versalhes', latitude=48.8049, longitude=2.1204, starts_at='2026-11-27T14:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=9) and a.period='afternoon';
  update public.activities a set title='Domaine National de Saint-Cloud — Lumières en Seine', place_name='Domaine National de Saint-Cloud — Lumières en Seine', latitude=48.843, longitude=2.216, starts_at='2026-11-27T19:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=9) and a.period='night';
  update public.activities a set title='Champs-Élysées', place_name='Champs-Élysées / Apple Store / Le Marais', latitude=48.8698, longitude=2.3076, starts_at='2026-11-28T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=10) and a.period='morning';
  update public.activities a set title='Transfer para o Aeroporto de Beauvais', place_name='Transfer para o Aeroporto de Beauvais', latitude=49.4544, longitude=2.1128, starts_at='2026-11-28T17:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=10) and a.period='afternoon';
  update public.activities a set title='Sintra — Palácio da Pena', place_name='Sintra — Palácio da Pena', latitude=38.787, longitude=-9.39, starts_at='2026-11-29T09:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=11) and a.period='morning';
  update public.activities a set title='Chiado', place_name='Chiado / Bairro Alto', latitude=38.7107, longitude=-9.14, starts_at='2026-11-29T15:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=11) and a.period='afternoon';
  update public.activities a set title='Jantar tranquilo em Lisboa', place_name='Jantar tranquilo em Lisboa', latitude=38.7107, longitude=-9.14, starts_at='2026-11-29T19:30:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=11) and a.period='night';
  update public.activities a set title='Oceanário de Lisboa', place_name='Oceanário de Lisboa', latitude=38.7636, longitude=-9.0942, starts_at='2026-11-30T10:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=12) and a.period='morning';
  update public.activities a set title='Parque das Nações', place_name='Parque das Nações / orla', latitude=38.763, longitude=-9.095, starts_at='2026-11-30T15:00:00' where a.day_id=(select d.id from public.trip_days d where d.trip_id=trip_id_var and d.day_number=12) and a.period='afternoon';
end $$;
